/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.95
 * Generated at: 2024-09-24 05:29:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-1.10.2.js\"></script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/ui/1.10.4/jquery-ui.js\"></script>\r\n");
      out.write("    <link href=\"https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  </head>\r\n");
      out.write("  <link\r\n");
      out.write("\r\n");
      out.write("    href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("    rel=\"stylesheet\"\r\n");
      out.write("    integrity=\"sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH\"\r\n");
      out.write("    crossorigin=\"anonymous\"\r\n");
      out.write("  />\r\n");
      out.write("  <body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("     <form action=\"loginForm\"  method=\"post\" class=\"row g-3 needs-validation\" >\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <label for=\"Name\" class=\"form-label\">Name</label>\r\n");
      out.write("          <input type=\"text\" class=\"form-control\" id=\"Name\" value=\"\" required name=\"name\" />\r\n");
      out.write("          <div  style=\"color: red;\" id=\"invalid-Name\">   </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <label for=\"Email\" class=\"form-label\">Emaill</label>\r\n");
      out.write("          \r\n");
      out.write("            <input\r\n");
      out.write("              type=\"email\"\r\n");
      out.write("              class=\"form-control\"\r\n");
      out.write("              id=\"Email\"\r\n");
      out.write("              name=\"email\"\r\n");
      out.write("              aria-describedby=\"inputGroupPrepend\"\r\n");
      out.write("              required\r\n");
      out.write("            />\r\n");
      out.write("            <div style=\"color: red;\" id=\"invalid-email\"></div>\r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <label for=\"mobile\" class=\"form-label\">Mobile Number</label>\r\n");
      out.write("          <input\r\n");
      out.write("            type=\"tel\"\r\n");
      out.write("            class=\"form-control\"\r\n");
      out.write("            id=\"mobile\"\r\n");
      out.write("            name=\"mobile\"\r\n");
      out.write("            value=\"\"\r\n");
      out.write("            maxlength=10\r\n");
      out.write("            minlength=10\r\n");
      out.write("           \r\n");
      out.write("            required\r\n");
      out.write("          />\r\n");
      out.write("          <div style=\"color: red;\" id=\"invalid-mobile\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <label for=\"dob\" class=\"form-label\">Date of Birth</label>\r\n");
      out.write("          <p> <input type=\"text\" id=\"datepicker-1\" name=\"dob\" required placeholder=\"MM/DD/YYYY\" readonly></p>\r\n");
      out.write("          <div style=\"color: red;\"  id=\"invalid-datepicker-1\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <label for=\"State\" class=\"form-label\">Qualification</label>\r\n");
      out.write("          <select class=\"form-select\" id=\"Qualification\" name=\"Qualification\" required>\r\n");
      out.write("            <option selected disabled value=\"\">Choose...</option>\r\n");
      out.write("            <option>SSC</option>\r\n");
      out.write("            <option>HSC</option>\r\n");
      out.write("            <option>Graduation</option>\r\n");
      out.write("            <option>BE</option>\r\n");
      out.write("          </select>\r\n");
      out.write("          <div style=\"color: red;\" id=\"invalid-option\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-6\" id=\"flexRadio\">\r\n");
      out.write("          <label for=\"State\" class=\"form-label\" style=\"margin-right: 25px;\">Gender</label>\r\n");
      out.write("          <div>\r\n");
      out.write("          <input class=\"form-check-input\" style=\"margin-right: 5px;\" type=\"radio\" name=\"gender\" id=\"flexRadioDefault1\" value=\"male\">\r\n");
      out.write("          <label class=\"form-check-label\" for=\"flexRadioDefault1\" style=\"margin-right: 20px;\">Male</label>\r\n");
      out.write("        \r\n");
      out.write("          <input class=\"form-check-input\" style=\"margin-right: 5px;\" type=\"radio\" name=\"gender\" id=\"flexRadioDefault2\" value=\"female\">\r\n");
      out.write("          <label class=\"form-check-label\" for=\"flexRadioDefault2\">Female</label>\r\n");
      out.write("          <div style=\"color: red;\"  id=\"invalid-gender\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <label for=\"password\" class=\"form-label\">Password</label>\r\n");
      out.write("          <input type=\"password\" class=\"form-control\" id=\"password\" required  name=\"password\"/>\r\n");
      out.write("          <div style=\"color: red;\"  id=\"invalid-password\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-6\">\r\n");
      out.write("          <label for=\"cPassword\" class=\"form-label\">Confirm Password</label>\r\n");
      out.write("          <input type=\"password\" class=\"form-control\" id=\"cPassword\" required />\r\n");
      out.write("          <div style=\"color: red;\" id=\"invalid-cpassword\" ></div>\r\n");
      out.write("          <!-- <div style=\"color: red;\" id=\"missmatch\" ></div> -->\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- <div class=\"col-12\">\r\n");
      out.write("          <div class=\"form-check\">\r\n");
      out.write("            <input\r\n");
      out.write("              class=\"form-check-input\"\r\n");
      out.write("              type=\"checkbox\"\r\n");
      out.write("              value=\"\"\r\n");
      out.write("              id=\"invalidCheck\"\r\n");
      out.write("              required\r\n");
      out.write("            />\r\n");
      out.write("            <label class=\"form-check-label\" for=\"invalidCheck\">\r\n");
      out.write("              Agree to terms and conditions\r\n");
      out.write("            </label>\r\n");
      out.write("            <div style=\"color: red;\">\r\n");
      out.write("             \r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div> --> \r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 d-flex justify-content-between\">\r\n");
      out.write("<!--           <button class=\"btn btn-primary\" id=\"submit\" type=\"submit\">\r\n");
      out.write("             <input type=\"\" />\r\n");
      out.write(" -->            \r\n");
      out.write("  <input type=\"submit\" value=\"submit\"  class=\"btn btn-primary\" id=\"submit\" />\r\n");
      out.write(" \r\n");
      out.write("          </button>\r\n");
      out.write("          <button class=\"btn btn-danger\" id=\"reset-form\" >\r\n");
      out.write("            Reset form\r\n");
      out.write("          </button>\r\n");
      out.write("          \r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("      	<form action=\"viewAll\" style=\"display: inline;\">\r\n");
      out.write("							<input type=\"hidden\" name=\"id\" value=\"<s:property value='id' />\" />\r\n");
      out.write("							<input type=\"submit\" value=\"View all\" class=\"btn btn-success my-2\" />\r\n");
      out.write("		</form>\r\n");
      out.write("		</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("      integrity=\"sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("     <script src=\"./Web-INF/JQuery/jquery-3.7.1.min.js\"></script> \r\n");
      out.write("   <script>\r\n");
      out.write("    /**\r\n");
      out.write("     * \r\n");
      out.write("     */\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("      $(\"#reset-form\").click(function () {\r\n");
      out.write("        form.reset();\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      var today = new Date();\r\n");
      out.write("      var dd = String(today.getDate()).padStart(2, \"0\");\r\n");
      out.write("      var mm = String(today.getMonth() + 1).padStart(2, \"0\"); //January is 0!\r\n");
      out.write("      var yyyy = today.getFullYear();\r\n");
      out.write("      today = mm + \"/\" + dd + \"/\" + yyyy;\r\n");
      out.write("\r\n");
      out.write("      var mobileFilter = /[6-9]{1}[0-9]{9}/;\r\n");
      out.write("\r\n");
      out.write("      function isValidMobile(mob) {\r\n");
      out.write("        return mobileFilter.test(mob);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("      $(\"#mobile\").on(\"input\", function () {\r\n");
      out.write("        const mob = $(\"#mobile\").val();\r\n");
      out.write("        console.log(mob.length);\r\n");
      out.write("\r\n");
      out.write("        // if (mob.length !== 10) {\r\n");
      out.write("        //   $(\"#invalid-mobile\").text(\"Please enter a valid number\");\r\n");
      out.write("        // } else {\r\n");
      out.write("        //   $(\"#invalid-mobile\").text(\"\");\r\n");
      out.write("        //   $(\"#mobile\").css(\"background-color\", \"white\");\r\n");
      out.write("        // }\r\n");
      out.write("        if (!isValidMobile(mob)) {\r\n");
      out.write("          $(\"#invalid-mobile\").text(\"Please enter a valid number\");\r\n");
      out.write("          \r\n");
      out.write("        } else {\r\n");
      out.write("          $(\"#invalid-mobile\").text(\"\");\r\n");
      out.write("          $(\"#mobile\").css(\"background-color\", \"white\");\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      $(\"#Name\").on(\"input\", function () {\r\n");
      out.write("        const mob = $(\"#Name\").val();\r\n");
      out.write("        \r\n");
      out.write("        if (mob.length === 0) {\r\n");
      out.write("          $(\"#invalid-Name\").text(\"Please enter a valid Name\");\r\n");
      out.write("        } else {\r\n");
      out.write("          $(\"#invalid-Name\").text(\"\");\r\n");
      out.write("          $(\"#Name\").css(\"background-color\", \"white\");\r\n");
      out.write("          \r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      var emailPattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,4}$/;\r\n");
      out.write("\r\n");
      out.write("        function isValidEmail(email) {\r\n");
      out.write("            return emailPattern.test(email);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      $(\"#Email\").on(\"input\", function () {\r\n");
      out.write("        const email = $(\"#Email\").val();\r\n");
      out.write("        console.log(email.length);\r\n");
      out.write("\r\n");
      out.write("        if (!isValidEmail(email)) {\r\n");
      out.write("          $(\"#invalid-email\").text(\"Please enter a valid Email\");\r\n");
      out.write("        } else {\r\n");
      out.write("          $(\"#Email\").css(\"background-color\", \"white\");\r\n");
      out.write("          $(\"#invalid-email\").text(\"\");\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      $(\"#cPassword\").on(\"input\", function () {\r\n");
      out.write("        const cPassword = $(\"#cPassword\").val();\r\n");
      out.write("        const password = $(\"#password\").val();\r\n");
      out.write("\r\n");
      out.write("        if (cPassword !== password) {\r\n");
      out.write("          $(\"#invalid-cpassword\").text(\"Password missmatch\");\r\n");
      out.write("        } else {\r\n");
      out.write("          $(\"#invalid-cpassword\").text(\"\");\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      $(\"#password\").on(\"input\", function () {\r\n");
      out.write("        \r\n");
      out.write("        const password = $(\"#password\").val();\r\n");
      out.write("        const cPassword = $(\"#cPassword\").val();\r\n");
      out.write("        if (cPassword !== password) {\r\n");
      out.write("          $(\"#invalid-cpassword\").text(\"Password missmatch\");\r\n");
      out.write("        } else {\r\n");
      out.write("          $(\"#invalid-cpassword\").text(\"\");\r\n");
      out.write("        }\r\n");
      out.write("        if (password) {\r\n");
      out.write("          $(\"#invalid-password\").text(\"\");\r\n");
      out.write("          $(\"#password\").css(\"background-color\", \"white\");\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("      $( \"#datepicker-1\" ).datepicker({\r\n");
      out.write("        maxDate:0\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      $(\"#datepicker-1\").on(\"change\", function () {\r\n");
      out.write("          console.log( $(\"#datepicker-1\").val());\r\n");
      out.write("          maxDate: new Date()\r\n");
      out.write("          // $(\"#invalid-datepicker-1\").css(\"background-color\", \"white\");\r\n");
      out.write("          \r\n");
      out.write("        if (today < $(\"#datepicker-1\").val()) {\r\n");
      out.write("          \r\n");
      out.write("            $(\"#invalid-datepicker-1\").text(`Please select a propar date`);\r\n");
      out.write("          }\r\n");
      out.write("          else{\r\n");
      out.write("            $(\"#invalid-datepicker-1\").text(``);\r\n");
      out.write("            $(\"#datepicker-1\").css(\"background-color\", \"white\");\r\n");
      out.write("          }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("      $(\"#Qualification\").on(\"change\", function () {\r\n");
      out.write("          \r\n");
      out.write("        if (!$(\"#Qualification\").val()) {\r\n");
      out.write("            $(\"#invalid-option\").text(`Please enter valid qualification`);\r\n");
      out.write("            $(\"#Qualification\").css(\"background-color\", \"red\");\r\n");
      out.write("          }\r\n");
      out.write("        else{\r\n");
      out.write("            $(\"#invalid-option\").text(``);\r\n");
      out.write("            $(\"#Qualification\").css(\"background-color\", \"white\");\r\n");
      out.write("        }\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      $(\"#flexRadio\").on(\"change\", function () {\r\n");
      out.write("          \r\n");
      out.write("        if ($('input[name=\"gender\"]:checked').val()) {\r\n");
      out.write("          $(\"#invalid-gender\").text(``);\r\n");
      out.write("          }\r\n");
      out.write("\r\n");
      out.write("      });\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
